### ISSUE TITLE
JS scratch doesn't use ES6 and there is no way to force it

### ISSUE THREAD

**Issue by nazar-pc** [dkandalov/scratch#37]
Any use of newer JS features in scratch results in error and breaks formatting. Any chance to make scratches take project level JavaScript version into account?

**Comment by dkandalov** [comment]
I can confirm there is an issue with JS highlighting showing errors in scratches (Build #IU-173.4674.33). This happens even after choosing language level for a scratch as JS1.8 (right click in the editor -> Change Language in the popup menu).

However, the scratch files of this plugin are now stored in the same location as built-in IntelliJ scratches. So this issue will affect all users of built-in scratches and it's probably a good idea to report it on yourtrack https://youtrack.jetbrains.com/issues/IDEA (because jetbrains have more resources than me and own the IJ API). I haven't found any relevant issues there, if you create one, please give a shout I'll upvote it :)

**Comment by nazar-pc** [comment]
So you're saying that there are some built-in scratches? I though this is purely plugin's feature.

**Comment by dkandalov** [comment]
Yes, https://www.jetbrains.com/help/idea/scratches.html 

This plugin was created few years before and then was changed to store files in the same location as built-in scratches.

**Comment by nazar-pc** [comment]
Thanks for clarification, opened upstream issue instead: https://youtrack.jetbrains.com/issue/IDEA-189084
